@startuml
'https://plantuml.com/class-diagram

class FlutterBinding {
  +initInstances()
  +scheduleFrame()
  +handleBeginFrame(Duration)
  +handleDrawFrame()
  +handlePointerEvent(PointerEvent)
  +handleSemanticsEnabledChanged()
  +handleAccessibilityFeaturesChanged()
  +handleAppLifecycleStateChanged(AppLifecycleState)
  +handleBuildOwnerChanged()
  +handleTextScaleFactorChanged()
  +handlePlatformBrightnessChanged()
}

@enduml