@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana



abstract class Widget {
  +Key? key
  +Element createElement()
  {static} +bool canUpdate()
}

class RootWidget extends Widget {
    + RootElement createElement()
    + RootElement attach()
}

interface RootElementMixin {
    + void mount()
    + void void assignOwner()
}

class RootElement extends Element implements RootElementMixin{
    + void mount()
    + void update()
    + void performRebuild()
    - void _rebuild()
}


abstract class Element implements BuildContext{
    + int depth
    + Object? slot
    + Widget? widget;
    + BuildOwner? owner;
}
@enduml