@startuml
!pragma layout smetana

participant WidgetsBinding


WidgetsBinding -> WidgetsBinding ++:attachToBuildOwner
create  RootWidget
WidgetsBinding -> RootWidget :new
WidgetsBinding -> RootWidget ++:attach
RootWidget -> RootWidget ++: createElement
create  RootElement
RootWidget -> RootElement : new
return

RootWidget -> RootElement ++:mount
note over RootElement: 123
RootElement -> Element ++: super.mount
return
RootElement -> RootElement ++ :_rebuild
RootElement -> Element  ++ :updateChild
Element -> Element  ++ :inflateWidget

Element -> View ++ :createElement
View -> StatefulElement ++ :new StatefulElement
StatefulElement -> View ++ :createState
return _ViewState
note right : 赋值给_state
note over StatefulElement
state._element = this
state._widget = widget
end note
return 返回 StatefulElement
return 返回 StatefulElement

Element -> ComponentElement ++ :mount
ComponentElement -> Element ++ :_firstBuild
Element -> State  ++ :initState
note over State  :"initState"
return
Element -> State  ++ :didChangeDependencies
note over State  :"didChangeDependencies"
return
Element -> ComponentElement ++ :_firstBuild
ComponentElement -> ComponentElement  :_firstBuild
ComponentElement -> Element  ++ :rebuild
Element -> StatefulElement  ++ :performRebuild
StatefulElement -> ComponentElement  ++ :performRebuild
ComponentElement -> StatefulElement  ++ :build
StatefulElement -> State  ++ :build
note over  State : build(BuildContext)
return
return
ComponentElement -> Element  ++ :updateChild
note over Element : 递归更新 Element 子树
return
note right  : _child

return
return
return
return



return _child = Element
return
RootElement -> RootElement :super.performRebuild
@enduml