@startuml
!pragma layout smetana

participant WidgetsBinding


WidgetsBinding -> WidgetsBinding ++:attachToBuildOwner
create  RootWidget
WidgetsBinding -> RootWidget :new
WidgetsBinding -> RootWidget ++:attach
RootWidget -> RootWidget ++: createElement
create  RootElement
RootWidget -> RootElement : new
return
loop 递归调用
RootWidget -> RootElement ++:mount

RootElement -> Element ++: super.mount
return
RootElement -> RootElement ++ :_rebuild
RootElement -> Element  ++ :updateChild
Element -> Element  ++ :inflateWidget

note over Element :  Element newChild = newWidget.createElement
note over Element :   newChild.mount(this, newSlot);

return newChild
end
return newChild
return newChild
note over RootElement: _child = Element
RootElement -> Element ++:super.performRebuild
note over Element: _dirty = false
return
return
return
@enduml