@startuml
set namespaceSeparator ::

abstract class "State" {
  -T? _widget
  -_StateLifecycle _debugLifecycleState
  -StatefulElement? _element
  +T widget
  +BuildContext context
  +bool mounted
  -bool _debugTypesAreRight()
  +void initState()
  +void didUpdateWidget()
  +void reassemble()
  +void setState()
  +void deactivate()
  +void activate()
  +void dispose()
  +Widget build()
  +void didChangeDependencies()
  +void debugFillProperties()
}

abstract class Widget {
  +Key? key
  +int hashCode
  +Element createElement()
  +String toStringShort()
  +bool ==(Object other)
  {static} +bool canUpdate()
}

abstract class StatelessWidget {
  +StatelessElement createElement()
  +Widget build()
}

Widget <|-- StatelessWidget

abstract class StatefulWidget {
  +StatefulElement createElement()
  +State<StatefulWidget> createState()
}

Widget <|-- StatefulWidget



abstract class RenderObjectWidget {
  +RenderObjectElement createElement()
  +RenderObject createRenderObject()
  +void updateRenderObject()
  +void didUnmountRenderObject()
}

Widget <|-- RenderObjectWidget

abstract class LeafRenderObjectWidget {
  +LeafRenderObjectElement createElement()
}

RenderObjectWidget <|-- LeafRenderObjectWidget

abstract class SingleChildRenderObjectWidget {
  +Widget? child
  +SingleChildRenderObjectElement createElement()
}

RenderObjectWidget <|-- SingleChildRenderObjectWidget

abstract class MultiChildRenderObjectWidget {
  +List<Widget> children
  +MultiChildRenderObjectElement createElement()
}

RenderObjectWidget <|-- MultiChildRenderObjectWidget

class ErrorWidget {
  {static} +Widget Function(InvalidType) builder
  +String message
  -FlutterError _flutterError
  {static} -String _stringify()
  +RenderBox createRenderObject()
}

LeafRenderObjectWidget <|-- ErrorWidget

abstract class ProxyWidget{
+Widget? child
}

Widget <|-- ProxyWidget

class RootWidget {
  +Widget? child
  +RootElement createElement()
  +RootElement attach()
}

Widget <|-- RootWidget



@enduml